package model.pojo;
// Generated 31/10/2019 16:27:54 by Hibernate Tools 3.6.0



/**
 * Noticia generated by hbm2java
 */
public class Noticia  implements java.io.Serializable {


     private int idnoticia;
     private String titulo;

    public Noticia() {
    }

    public Noticia(int idnoticia, String titulo) {
       this.idnoticia = idnoticia;
       this.titulo = titulo;
    }
   
    public int getIdnoticia() {
        return this.idnoticia;
    }
    
    public void setIdnoticia(int idnoticia) {
        this.idnoticia = idnoticia;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }




}


